# use container on EC2, other options availible (venvs) [https://docs.travis-ci.com/user/reference/overview/]
sudo: false   
dist: trusty

language: python
python:
  - "3.7"

notifications:
  email: never

install:
  - pip install pytest pytest-cov codecov

env:
  - CODECOV_TOKEN="4d00e3f3-dcd0-4e7b-ba6d-e2a5eae2c59f"  #get token from https://codecov.io/ --> add new repository

script:
  - pytest --cov=./ --cov-report xml
  # - coverage run dummy_test.py

after_success:
  - codecov   # go to https://codecov.io/ to see report (have to log in with github)
  #- codecov -t the_repository_upload_token #for private repositoryory